### ISSUE TITLE
Lots of PHP Warnings on Wiki Hooks

### ISSUE THREAD

**Issue by JoeHorn** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#106]
Hi,

I have sites run with Mediawiki 1.28.2 , after installed this extension ( Wysiwyg 1.5.6_0 [B551+09.02.2017], CKEditor 4.5.9 (revision a35abfe) ).
I found lots of PHP Warnings like these : 
> PHP Warning:  Parameter 1 to CKeditor_MediaWiki::onOutputPageParserOutput() expected to be a reference, value given in __MEDIAWIKI_ROOT_DIR__/includes/Hooks.php on line 195
> PHP Warning:  Parameter 1 to CKeditor_MediaWiki::onBeforePageDisplay() expected to be a reference, value given in __MEDIAWIKI_ROOT_DIR__/includes/Hooks.php on line 195

Should we change those functions ?
Such as change
`public static function onBeforePageDisplay( &$out, &$text ) {`
to 
`public static function onBeforePageDisplay( $out, &$text ) {`

**Comment by riparap** [comment]
Declaration of onBeforePageDisplay should be [according to documentation as it is now](https://www.mediawiki.org/wiki/Manual:Hooks/OutputPageParserOutput).  

It may be that this is caused by version of php you are using. It has worked properly in my test env. at least with php versions 5.5.15 and 7.2.5.
