### ISSUE TITLE
Historylink

### ISSUE THREAD

**Issue by gtbu** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#108]
I try to add the BrowserHistoryLink extension and put into the sourcecode
`<historylink type="back">Go Back 1 Page</historylink>`  

but ckeditor makes me
`<historylink> <span class="na">type=</span><span class="s">"back"</span> <span class="nt">/></span></historylink>`
 and then a css (which all functions under MW1.19.24 and cavendish-skin)   /historylink> 
is simply erased.  -- and many similar automatic corrections - how can i switch that off ?

**Comment by riparap** [comment]
Your version of MW is rather old, this version of WYSIWYG has never been tested against that version of MW. What version of wysiwyg are you using? I tested BrowserHistoryLink with MW1.29.2 and tag historylink is converted as special-element in wysiwyg mode (as it should be). 

Version of wysiwyg: `CKEditor 4.6.2 (revision 20af917). Version 1.5.6_0 [B551+09.02.2017]`

However, there are some compatibility issues with BrowserHistoryLink and MW >= 1.21 because BrowserHistoryLink is using some deprecated functions, which have been removed.

Maybe you could test newer version of MW?

**Comment by gtbu** [comment]
I testet Your newest Ckeditor with mw1.27.4 - and i had that behaviour. Ckeditor produces < span.. which i want to stop. The module BrowserHistoryLinks does not function with ww1274 - i have to convert an old sql and saw the spans.
