### ISSUE TITLE
in MW 1.23.5 the editor ist reformatting the category link

### ISSUE THREAD

**Issue by Man-in-Black** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#22]
Hello together,

i've updated my MW to Version 1.23.5 and wanted to use the WYSIWYG-Editor.
It works for the most pages, but if I use categorys for sorting of the pages, it reformats the category-link so that every entry is listed under "C".

Is it possible to fix this problem?

**Comment by riparap** [comment]
I updated my test env. to MW 1.23.5: to me it seems like category is working in the same way as with MW 1.22.12 with wysiwyg editor. I can add categories on page and categories can be viewed and editied by clicking the "C" element in wysiwyg editing mode. If I go to page "Categories" of MW, I can see my test page categorised under those categories I have specified the page to belong to. 

I am not quite sure what kind of situation you are referring to ...so do you mean this:
*you have page where there is one or more categories defined on page, when page is viewed, categories are displayed normally as "text" => no problems
*when you switch to edit mode of wysiwyg editor with this page, category definitions are converted into elements marked with "C" image => this is the location of "problem" which you are referring to?

This is not MW version specific issue or an error. At current moment this is how category function of this wysiwyg version behaves by default. You are not able to see the text of category elements directly in wywisyg editing mode. You can see the category of each "C" element in wywisyg editor by double clicking the "C" image, which will then open dialog to edit the category definition.

I would assume that it is possible to change this behaviour somehow, but currently I do not have enough knowledge to do this because it will require modifications in various parts of php and java script codes. Perhaps one easier option would be to display category as "help" text of "C" image when pointer is placed on top it, but I do not know how to do this either. 

...help and suggestions about how to modify this are highly appreciated.

If this is not the case with your installation, could you please give a little more detailed description about the problem you have...

**Comment by Man-in-Black** [comment]
My problem is not how a category is displayed in the editor.
My problem ist, that when I save a page, the page is displayed unter the character "C" in the special site for categories.
An example: If I edit a page with the title "Testpage", it should be displayed under the character "T" in the categories site. But if I save the page with the WYSIWYG-Editor, the page is sorted unter the character "C".

I hope that this example explains my problem in the correct way.

**Comment by riparap** [comment]
Name of the page does not make the page visible under categories of MW, you have to define category on page in order to get it visible on special page of "Categories"... I quess you already know this.

Sounds like there is a "sortkey" defined with category definition on your "Testpage". This can be checked in source editing mode. This wikitext definition [[Category:Testpage|C]] will act like your "Tespage" sorting the page under letter "C" in category "Testpage". All these definitions will sort page normally under letter "T" in category "Testpage": [[Category:Testpage]], [[Category:Testpage|T]].

It seems that for some reason when you open an existing page in wysiwyg editor which has categories defined and save it without modifying the category, it will convert category definitions into this kind of string:  [[Category:Testpage|Category:Testpage]] => page will be sorted under letter "C". It is some kind of problem with wikitext=>wysiwyg parser. At this moment I do not have a glue when this has started to happen, you are the first one who has noticed this. Based on my test it works similarly also with MW 1.22.12.

**Comment by riparap** [comment]
This is possibly caused by modification dated 23.08.14 "Merge pull request #16 from Varlin/patch-8, Fix unwanted caps" (commit: 83b81d5ca2a6493a72f41c709f1dbdfd4bec5bb7 [83b81d5])" which is related to unwanted upper caps of link names, they are using [[...]] in same way as category definitions. I quess this modification has to be cancelled, I have to test this more.

**Comment by riparap** [comment]
This issue has been fixed by cancelling abowe mentioned modification.

**Comment by Man-in-Black** [comment]
Hi,

I've updated my local WYSIWYG installation and it worked. The pages are sorted correctly within the category site.

Thank you very much for the fast solution of my problem.
