### ISSUE TITLE
Fatal Error: Cannot access protected property OutputPage::$styles

### ISSUE THREAD

**Issue by atrus1701** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#23]
I am getting the following error when installing this plugin:

Fatal error: Cannot access protected property OutputPage::$styles in /home/wikiuncc/public_html/test/extensions/WYSIWYG/CKeditor.body.php on line 191

I have commented out the foreach statement on line 191 of CKeditor.body.php and it seems to work now.  The OutputPage::$styles was an empty array, so for my purposes, it's not needed but it would be great if this could get fixed in future versions.

**Comment by riparap** [comment]
There are installations using branch "CKeditor_v4" without problems. Could this be some kind of environment specific issue...  

I am wondering what is the version of wysiwyg you are using... Would you be so kind and give a little more detailed information about versions of components of your installation: MW, PHP, database, web server, wysiwyg.

In what kind of situation you get problems with this issue (f.ex when starting up mediawiki ... or when starting editing of page in wysiwyg mode ...)?

**Comment by LunaticMuch** [comment]
I have the same issue:

Fatal error: Cannot access protected property OutputPage::$styles in /var/www/html/wiki/extensions/WYSIWYG/CKeditor.body.php on line 191

These below are my env details:

MediaWiki   1.24.0
PHP 5.5.9-1ubuntu4.5 (apache2handler)
MySQL   5.5.40-0ubuntu0.14.04.1
WYSIWYG extension   1.5.6_0 [B551], based on this version, modified further, using CKEditor 4.4.5 (revision 25cdcad)

**Comment by riparap** [comment]
Ok... I did not notice that there already was this issue open, when I created new one #31 :). I will close  issue #31 because it is dublicate with this #23.

This will happen with MW 1.24. In MW 1.24 $styles variable has been changed to be "protected" in includes/OutputPage.php. This causes error in CKeditor.body.php (code somewhere  on lines ~192-218 depending strongly on version of file.... = lines  starting with "$inlineStyles = array();" ....... until into end of "foreach($inlineStyles as $media => $css ) {" block).

One workaround would be to change MW variable "styles" in includes/OutputPage.php to be "public". If you choose to do this, you will do it at your own risk, because I am not aware of security effects of this kind of modification. Variable has been declared as "public" in MW versions <=1.23.

Other workaround is to comment out lines 191-211 of CKeditor.body.php to make wysiwyg start. With my test page and FireFox, html code produced was still the same but I guess that code block is needed and can not just be deleted?

MW support desk thread:
https://www.mediawiki.org/wiki/Thread:Project:Support_desk/Protected_variable_styles_of_includes/OutputPage.php_vs._extension_using_it

MW bug tracker T76461:
https://phabricator.wikimedia.org/T76461

I am wondering if lines ~191-211 in CKeditor.body.php are needed at all with current browsers and updated CKeditor. Can it be that lines have been added there because of some older version of IE together with older version of CKeditor?    ... My current plan to fix this is to comment out those lines permanently.

**Comment by bruce1949** [comment]
I have the same problem, Wiki version: 1.24.1 php 5.5.15, mysql:5.6.20, I accept your comment, to comment out lines 191-211 and I experienced another error

Parse error: syntax error, unexpected '}' in D:\xampp\wiki\extensions\WYSIWYG\CKeditor.body.php on line 214
If I comment out lines 191-214, I can edit pages some warning messages is showed on the top of every pages;

Notice: Undefined variable: inlineStyles in D:\xampp\htdocs\wiki\extensions\WYSIWYG\CKeditor.body.php on line 216

Warning: Invalid argument supplied for foreach() in D:\xampp\htdocs\wiki\extensions\WYSIWYG\CKeditor.body.php on line 216

Do we have new solution now?

BTW, This is the best wiki editor I used. Thanks a lot for your contribution, Very appreciated.

**Comment by riparap** [comment]
Thanks :-)

Based on my test I think you have commented out too much or too little in CKeditor.body.php. You should leave line $inlineStyles = array(); uncommented. If you comment that line out but leave trailing "foreach($inlineStyles as..." uncommented, then you will get error you described... at least that happens in my environment.   ....so in your case I think you should also comment out "foreach($inlineStyles as.." -block too.

Other way to fix this issue is to leave file CKeditor.body.php unmodified and change $styles variable from "protected"  back to "public" in includes/OutputPage.php. This has disadvantage that when MW is updated, you have to do same fix again.

I am just wondering if that rearranging of styles in CKeditor.body.php is needed at all anymore with current browsers. Simplest final solution would be to comment that part out completely, but I have been unwilling to do it because I am not sure if it is still needed or not.

**Comment by bruce1949** [comment]
Thanks a lot, As an IT guy, I am willing to contribute on the project and want to share my knowledge to others, But I know little about PHP programming, and I am learning to promote my PHP, I would like to do something when I can,

Thanks a lots for your help.

**Comment by bruce1949** [comment]
This is a update message.
I think I make it successfully with your instruction, Thanks a lot, in my files, I comment out lines from 194-214,

Thanks a lot

**Comment by hbcodeXCI** [comment]
Hello 

The extension is work now perfectly but i want if i can not use this extension in some pages means the extension work in all the pages except some pages.

Thanks a lot.

**Comment by bruce1949** [comment]
Thanks a lot for your update. I will try it on my wiki, thank you everything.

Regards,
Bruce

Date: Wed, 22 Apr 2015 02:10:45 -0700

**Comment by fullduplex1** [comment]
as line write just before foreach loop
        if(!empty($out->styles) and is_array($out->styles))

**Comment by riparap** [comment]
Thanks, this workaround has been included in branch CKeditor_v45 "Version 1.5.6_0 [B551+01.09.2015]".

**Comment by riparap** [comment]
HilmiStage: If you would like to exclude some pages from wysiwyg so that you  can edit them using wikieditor, you can use variable $wgFCKEditorExcludedNamespaces in your LocalSettings.php file.
F.ex: $wgFCKEditorExcludedNamespaces[] = NS_MEDIAWIKI;
