### ISSUE TITLE
Possible source code corruption

### ISSUE THREAD

**Issue by vadamovsky** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#38]
We have a very long page which starts with:
`<center>'''[[Page1|Page 1]]''' &nbsp;&nbsp;|&nbsp;&nbsp; '''[[Page2|Page 2]]'''</center>`

This is a valid code that can be transformed to HTML and back to the source.

The problem is that while converting from wiki-source to HTML the button <b>Source</b> is enabled before the transformation is done. This enables to me start the opposite HTML to wiki-source transformation before the previous transformation to HTML is done.

This will result in a corrupted source because the HTML is inserted as a wiki-source:
`<center><b><a href="Page1">Page 1</a></b> &#160;&#160;|&#160;&#160; <b><a href="Page2">Page 2</a></b></center>`

The problem can be triggered even when clicking on the <b>Source</b> button for the first time right after the page with the editor is loaded.

To avoid the problem I have to wait few seconds after each wiki-source to HTML transformation before I can click to the <b>Source</b> button again. And as I said, this applies even for the first transformation which is started when the page with the editor is loaded.

I have find out that if I click to the <b>Source</b> button to trigger the HTML to wiki-source transformation too early the transformation is done correctly, the correct wiki-source is displayed but immediatelly after that it is replaced with the HTML code.

It looks like there are running some asynchronous calls which will replace the correct wiki-source with an HTML code.

I have also find out that the funcion <b>toHTML</b> in <i>extensions\WYSIWYG\ckeditor\plugins\mediawiki\plugin.js</i> is called twice when transforming from wiki-source. Is there a reason for this?

The best solution would be to enable the <b>Source</b> button after all the async calls are done.

Also, I would hide (or disable) the textarea during the transformation to prevent the user to edit the not-fully-transformed page.

There is:

```
//textarea.hide();
```

in <i>extensions\WYSIWYG\ckeditor\plugins\mediawiki\plugin.js</i>, but I was unable to show the hidden textarea after the transformation.

Maybe you will have better luck.

**Comment by riparap** [comment]
It seems there are 3 slightly different ways for wikitext->html conversion:
1. When edit link of page is pressed and wysiwyg opens.
2. When source button is pressed in source view
3. When toggle -link is pressed in source view.

All of them work slighly different way. When source button is pressed in source view, contents of wikitext window is copied into wysiwyg window "as it is". This somehow starts call of toHML which then takes wikitext from wysiwyg window (=1. call of toHTML), converts it to html, placing result in same wysiwyg window (2. call of toHTML). As you also noticed there is two calls to toHTML, but I could not figure out how they are started, I suspect they are triggered by events of CKeditor. I quess wysiwyg works like this by design. 

I made some modifications (version B551+05.01.15)) which tries to keep "wrong" window hidden during wikitext->html conversion. Fix also tries to display toggle link in little more restricted way. Perhaps you could test if it works any better now....  

I was unable to modify page opening when wysiywg opens for the first time. It seems to me that CKeditor tries to keep source button disabled until html code appears in wysiwyg window (until 'mode' is ready), 

I could not find any good event which could be used to store code which would disable source button in program. Those that I tested fires too early when source button still is disabled by CKeditor. And with "mode" trigger when wysiwyg mode is active, html contents was already properly placed in wysiwyg and source button was then enabled by CKeditor. ...It may be that my pages are too short for your problem to appear

i wonder if there is a way to keep source button of CKeditor active but defined so that it is disabled by default in wysiwyg mode. It could then be enabled by program after page is in html format and opened in wysiwyg (mode trigger) ..but perhaps this is too early based on your explanation. I could not find any other event that would tigger later than "mode". If there are none, then one option would be timer delay but this may be somewhat unreliable and perhaps somethimes annoying in case it is not needed.

Another possibility might be readOnly / setReadOnly -options of CKeditor... this would require more testing, because changing mode causes reload of editing area... that may have some kind of effect in flow of actions in programs.

We should have a CKeditor expert, this may be piece of cake when one just knows how to do it :)

**Comment by vadamovsky** [comment]
Can you sand me an email? I would like to discuss with you some possibilities to fix this issue:

&lt;My GitHub ID&gt;@gmail.com

Thank you.

**Comment by riparap** [comment]
Perhaps I should have created evaluation branch for this... I have cancelled this modification, because it seems not to work at all with certain pages.

**Comment by vadamovsky** [comment]
This issue has been resolved. Thank you.

**Comment by riparap** [comment]
This modification is included in version "1.5.6_0 [B551+12.01.2015]".
