### ISSUE TITLE
Bug when there is a space in a link url

### ISSUE THREAD

**Issue by Varlin** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#44]
Hello. I noticed that it is not possible to use a link with an url containing a space.
Because of the syntax, ie [url text], it is obvious there can be no "real space" (just " ") inside "url".
But the problem is : when using %20 for a space, it is replaced by the parser to a " ".
(So for instance, this url can't be reached : http://82.204.82.216/iirelogo/IIRE%20new%20logo-jpg145px.jpg )
I don't know if this problem is connected with this issue https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/issues/36 or not

**Comment by riparap** [comment]
I quess problem is in link dialog because it is converting %20 to space, but is not doing it other way around. It does convert space to undescore which will corrupt external link names with spaces. I'll try to test it some more...

**Comment by riparap** [comment]
Problem was not in link -dialog alone. I am not  100% sure where proper place for html decode/encode is :-), but I was anyway able to fix this problem. I am not sure if other kind of special characters in name of link could still cause problems or not. 

Modification is in branch "CKeditor_V4_HtmlComments" because there are also some additional fixes I have been working with. I hope they work without problems. I will at some point later merge it to "offical" branch "CKeditor_V4".

**Comment by riparap** [comment]
This has been merged into branch CKeditor_v4 at 24.01.2015.
