### ISSUE TITLE
tabletools?

### ISSUE THREAD

**Issue by realdadfish** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#72]
A quick question: Is there any particular reason why the `tabletools` extension is not enabled by default? I enabled it and made a quick test, and apparently it does what it should (adds / removes Wiki syntax when the table structure is modified).

What would have been the alternative to `tabletools` when it comes to editing tables, in the current release?

**Comment by riparap** [comment]
I do not know any alternatives to tabletools- plugin of ckeditor which could be used with ckeditor... except editing table in source/wikitext view, which might not be the most user friendly alternative :)

Plugin tableresize is included and enabled (=change width and height of columns).

Tabletools plugin seems to be included with downloaded ckeditor bundle within wsiwyg but it has not been enabled by config.js. I have not enabled it nor selected all possible other plugins with ckeditor bundle partly because I tried to follow the original build of ckeditor version 3.6 which was integrated with ckeditor earlier and partly because  I do not have possibility to test compatibility of all of the plugins with wysiwyg. Problem with these extra plugins is that they will inject html code on page. Depending on what kind of html code is produced and in what kind of context it appears in relation to wikitext code, it may make wysiwyg crash when pages are loaded or source/wysiwyg mode toggled. Wysiwyg seems to be rather sensitive to this kind of issues so it may be that what works with my test page, may not work with other kind of pages you may have.

Having html code on final wiki page has not been the orginal design idea when they have built wysiwyg editor, idea has been to make ckeditor produce wikitext code compatible with mediawiki. I know that this is not anymore fully true with current version of wysiwyg. Also different users have different ways to edit pages so that some will anyway insert html code on page using source view.

If you have tested tabletools plugin and found that it works properly I guess there are no reasons why you could not keep using that plugin with wysiwyg. However, I am still little hesitant to enable it by default unless we get more feedback about how it works.
