### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by zigbomb** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#83]
Database issues occur when using the submit button in the editor. The page does indeed get submitted and saved, but on the initial re-direct after submitting you are presented with a database error.
Visual support: https://gyazo.com/878a91765cc44f8a462bece084624a85.png
I couldn't find any help for this anywhere besides here. I know this isn't the proper sue of the issue tabs, but I really need help with this, what did I do wrong?

**Comment by riparap** [comment]
Usually, wysiwyg saves garbage in case something goes wrong in a way that conflicts mediawiki syntax. I have not heard before what wysiwyg causes database problems with MW.  What is your opsys, version of MW, database, PHP and wysiwyg?
Could you try disabling wysiwyg and edit pages with editor of MW, does this problem occur then?

**Comment by zigbomb** [comment]
1.26 MW, no clue about the database, or PHP, and the wysiwyg editor is ripped straight from the github,

**Comment by zigbomb** [comment]
Any help here please, lol

**Comment by riparap** [comment]
There are many branches of wysiwyg available. For MW1.26 you have to use bundle of  branch "wysiwyg_mw126", it is the only one which may work with MW1.26. Also this branch may still have some issues which have to be fixed in order to make it fully compatible with MW1.26.

**Comment by zigbomb** [comment]
Hm, maybe that's what I didn't do. I just grabbed the zip straight off the github, didn't check for any branch in particular.

**Comment by zigbomb** [comment]
I've done a fresh install once again. Installed Mediawiki 1.26.2, installed semantic, and it's mediawiki extension and now the editor isn't even showing up.
It's there in my versions page, any ideas why?
I have it setup right in my LocalSettings.php

**Comment by riparap** [comment]
Problem is with async. loading of javascripts in MW1.26. With branch wysiwyg_mw126 you can try adding following variable  in your LocalSettings.php:
$wgFCKEditor_delay_addonloadhook = 500;
Value is milliseconds, if 500 does not help, try 1000 or 2000. You can also try IE11 instead of FireFox or Chrome, in my tests, before this variable was added, IE worked better than FF or Chrome with MW1.26.

Perhaps you could also try to test bundle of latest branch wysiwyg_mw126_rsl, which is trying to use resourceloader of MW. This bundle is not using variable $wgFCKEditor_delay_addonloadhook anymore. This bundle contains fix which is hybrid solution where some javascripts are injected into page direclty, some are loaded using resourceloader of MW.

About Semantic which comes with wysiwyg bundle: semantic extension is not manadatory with wysiwyg because wysiwyg does not fully support it. You can ignore semantic and install wysiwyg and wikieditor extensions only.

**Comment by zigbomb** [comment]
I did this, it's up and it's still giving me a database error on submit, I'm not sure what was causing this, but we've switched mediawiki software anyways. Sorry.
