### ISSUE TITLE
Blank line is added before the text

### ISSUE THREAD

**Issue by Varlin** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#92]
Follow these steps to reproduce the bug : 
1- switch to source view
2- place the cursor/caret at the very beginning of the text
3- switch back to WYSIWIG view
4- switch to source view : the cursor is before the text, on an unwanted blank line that has been added by the editor

It is due to plugin textselection (when deactivated, no blank line).

I think that, between steps 3 and 4, the focus is on an element that should not have focus, provoking an error with textselection.
I tried to control focus with some JS tweaks in textselection/plugin.js but : fail

**Comment by riparap** [comment]
You are right, that procedure will add extra blank line with each sequential switch between modes (with FF).

The way how textselection plugin works is to insert some temporary token in place of cursor before switching mode and then jump to that place and remove token in other mode. Textselection plugin is "heavily" modified for wysiwyg, because of the way wysiwyg switches from source mode to wysiwyg view. I have had to remove the effect of textselection plugin in this direction. It should have effect only in wysiwyg - source mode direction. It may be that this fix is not fully reliable.

But on the other hand I do not recall that this problem has been there before the latest major modifications (=upgrade version of CKeditor and usage of standard dataprocessor of CKeditor). It may  be that removing the custom dataprocessor may have something to do with this. Third thing may be version of textselection plugin compared to upgraded version of CKeditor.

I have not upgraded the textselection plugin when version of CKeditor was lifted. Upgrading version of textselection plugin would mean that current modifications of it must be reapplied manually to newer version. If I remember right, they are only commenting out some code of blocks of textselection - plugin. I am not sure, but perhaps this might be worth trying. 

....It is little difficult to tell what is the real version of textselection- plugin, page of plugin states 1.05 but inside file version string is still 1.04. I can try to upgrade the plugin, it should be fairly simple thing to reapply modifications I have made.

**Comment by riparap** [comment]
@Upgrading textselection plugin will not fix this problem.

It seems like with IE11 it works ok. With Chrome it adds only one extra empty line. With FF extra empty line is added with each repeated wysiwyg-source toggle. 

Visible difference is that with IE it keeps focus on editor window in both modes (cursor can be seen on line). Chrome looses focus from editor window when switching from source to wysiwyg mode. With FF it also looses focus in this direction. 

With FF if I manually set cursor on some place in wysiwyg mode before pressing source-button, empty lines will not be added with repeated toggles of source-wysiwyg modes.

Extra empty lines with FF are somehow caused by method createBookmark of CKeditor and later removal of it in textselection plugin, which for some reason in unfocused situation leaves extra `&nbsp;` in place of bookmark. It is left on line because it is after the end of span-element (="second" bookmark added). It may be remnant of a earlier bookmark, but I can not figure out how this is possible. This extra `&nbsp;` will not be removed, when "second" bookmark is removed because it is outside of span- element.  This creates extra empty line.

It also looks like test of focus which plugin does does not work properly so that plugin starts bookmark creation also when focus is not in editor area and source button is pressed. With first press of source button test of focus works and plugin does not run, but after this plugin runs every time button is pressed (in direction wysiwyg-wikitext) regardless where focus is.

I am able to prevent FF for adding extra empty lines by adding `editor.focus();` in `editor.on('beforeGetModeData'...` of texselection plugin or by adding `editor.focusManager.blur();` in the end of `beforeModeUnload`.

Compared to IE11, FF and Chrome both have still one empty first line after wysiwyg-source toggle. This empty line is not caused by textselection plugin because disabling plugin will not remove that line.

**Comment by riparap** [comment]
I have made modification based on this in version Version 1.5.6_0 [B551+16.08.2016]. I used `editor.focusManager.blur();`. Hopefully it helps in your wiki too.

**Comment by Varlin** [comment]
Sorry for the delay in the answer...
Thanks, I just tried this and it's perfect !
