### ISSUE TITLE
Numbered Lists Do Not Retain Numbering

### ISSUE THREAD

**Issue by glodoski** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#93]
When creating a numbered list with indented sub-points, the numbering starts back at 1 after the sub-section.  The formatting looks correct when in the editor, but upon saving the page and viewing it normally, the numbering looks like so:

1.) First Point
2.) Second Point
_____ 1.) Further Information
1.) Third Point

**Comment by riparap** [comment]
In wikitext format is this what you are trying produce?
`#Number`
`#Number2`
`##Number1, next level`
`#Number3`

...which  should be displayed like this when page is viewed:
`1. Number1`
`2. Number2`
`1. Number1, intended`
`3. Number3`

If edited with wysiwyg last line does not have number "3." it has number "1."

Also this wikitext seems to have problems:
`*level1`
`**Level2` 
`***Level3` 
`**level2` 

Reason seems to be extra empty line which can be seen when f.ex source button is toggled few times. I have not yet had time to find out what is causing this,

**Comment by glodoski** [comment]
That is exactly the issue.  
Thank you for all your work on this plugin! It's a fantastic addition to our Wiki.

**Comment by riparap** [comment]
Thanks. This seems to be browser issue, for some reason element tags of lists (ul, ol, li) are in uppercase in browser but in program of wysiwyg they are tested against lower case variants. I do not understnad why and when this has stopped working..... or can it be so that this problem has been in wysiwyg all the time but it just was discovered now? 

This has been fixed in Version 1.5.6_0 [B551+09.11.2016].

**Comment by glodoski** [comment]
Marking this issue as closed, as the new plugin version does indeed fix the issue. 

Thank you for the prompt response!  I have verified expected functionality on both Mac/PC Firefox & Chrome, as well as IE 11 on PC.
